echo ----------+----------+----------+----------+----------
echo ...
$my_dir/bin/hadoop dfs -rmr $my_fsd/MR1/output
echo ...
$my_dir/bin/hadoop dfs -rmr $my_fsd/MR2/output
echo ...
$my_dir/bin/hadoop dfs -rmr $my_fsd/MR3/MR31/output
echo ...
$my_dir/bin/hadoop dfs -rmr $my_fsd/MR3/MR32/output
echo ...
$my_dir/bin/hadoop dfs -rmr $my_fsd/MR4/MR41/output
echo ...
$my_dir/bin/hadoop dfs -rmr $my_fsd/MR4/MR42/output
echo ----------+----------+----------+----------+----------

