echo ...
$my_dir/bin/hadoop dfs -rm $my_fsd/MR4/MR42/input/*
echo ...
$my_dir/bin/hadoop dfs -cp $my_fsd/MR4/MR41/output/part* $my_fsd/MR4/MR42/input/
#echo ...
#$my_dir/bin/hadoop dfs -cat $my_fsd/MR4/MR42/input/*

